### ISSUE TITLE
EmailType 'HTML' does not work.

### ISSUE THREAD

**Issue by ranjeetsinha13** [luongvo/GmailBackground#1]
If the email type is set as TYPE_HTML, it does not work and the mail is sent as plain text only.

**Comment by ArthurAttout** [comment]
Did you find any solution for this issue ?

**Comment by ranjeetsinha13** [comment]
This [link](https://github.com/yesidlazaro/GmailBackground) works perfectly. So I forked this one and added whatever I needed to the project. I am not sure why it does not work in your repo.

**Comment by luongvo** [comment]
@ranjeetsinha13 ok, I'll spend my time to work on it

**Comment by BenjaminGsmg** [comment]
@luongvo  
Hi Luong,
I just tried the HTML type with the latest version (2.0.2) but it's still just plain text. Have you had any success with working on this topic?

**Comment by jumaris88** [comment]
Try this 
```

MailcapCommandMap mc = (MailcapCommandMap) CommandMap

			.getDefaultCommandMap();

        mc.addMailcap("text/html;; x-java-content-handler=com.sun.mail.handlers.text_html");

        mc.addMailcap("text/xml;; x-java-content-handler=com.sun.mail.handlers.text_xml");

        mc.addMailcap("text/plain;; x-java-content-handler=com.sun.mail.handlers.text_plain");

        mc.addMailcap("multipart/*;; x-java-content-handler=com.sun.mail.handlers.multipart_mixed");

        mc.addMailcap("message/rfc822;; x-java-content-handler=com.sun.mail.handlers.message_rfc822");

        CommandMap.setDefaultCommandMap(mc);
```

**Comment by luongvo** [comment]
@ranjeetsinha13 @ArthurAttout @BenjaminGsmg this is resolved, check newest version
