### ISSUE TITLE
Could not find com.github.luongvo:GmailBackground:2.0.2.

### ISSUE THREAD

**Issue by rajgar114** [luongvo/GmailBackground#11]
file:/F:/Android/Sdk/extras/m2repository/com/github/luongvo/GmailBackground/2.0.2/GmailBackground-2.0.2.pom
    file:/F:/Android/Sdk/extras/m2repository/com/github/luongvo/GmailBackground/2.0.2/GmailBackground-2.0.2.jar
    file:/F:/Android/Sdk/extras/google/m2repository/com/github/luongvo/GmailBackground/2.0.2/GmailBackground-2.0.2.pom
    file:/F:/Android/Sdk/extras/google/m2repository/com/github/luongvo/GmailBackground/2.0.2/GmailBackground-2.0.2.jar
    file:/F:/Android/Sdk/extras/android/m2repository/com/github/luongvo/GmailBackground/2.0.2/GmailBackground-2.0.2.pom
    file:/F:/Android/Sdk/extras/android/m2repository/com/github/luongvo/GmailBackground/2.0.2/GmailBackground-2.0.2.jar
    https://dl.google.com/dl/android/maven2/com/github/luongvo/GmailBackground/2.0.2/GmailBackground-2.0.2.pom
    https://dl.google.com/dl/android/maven2/com/github/luongvo/GmailBackground/2.0.2/GmailBackground-2.0.2.jar
    https://jcenter.bintray.com/com/github/luongvo/GmailBackground/2.0.2/GmailBackground-2.0.2.pom
    https://jcenter.bintray.com/com/github/luongvo/GmailBackground/2.0.2/GmailBackground-2.0.2.j

**Comment by luongvo** [comment]
@rajgar114 did you retry?

**Comment by fatahfattah** [comment]
Same issue exists for me

**Edit:** forgot to add "maven { url "https://jitpack.io" }" all good now

**Comment by goffity** [comment]
I have same problem. But I added maven { url "https://jitpack.io" } in build.gradle at root level.
but I can found com.github.luongvo:GmailBackground:2.0.2 in https://jitpack.io/

I try delete .gradle in home folder for delete cache.

What dose I wrong.

Updated: I solved when I restart android studio and re sync.
