### ISSUE TITLE
Change messages

### ISSUE THREAD

**Issue by marcellocamara** [luongvo/GmailBackground#16]
Can you add features methods to change messages that you default created ?
Example : I need to change the AlertDialog message language, the toast fail/sucess message... etc.

You think is a good idea to fork your repository and made my changes to portuguese language?

**Comment by luongvo** [comment]
@marcellocamara plz look at the newest version `2.1.1`, we have no message config anymore, the lib just return the callback and you have to control what should you do after success or fail by yourself

**Comment by luongvo** [comment]
https://github.com/yesidlazaro/GmailBackground/issues/41
