### ISSUE TITLE
No Conection Error

### ISSUE THREAD

**Issue by kevin-fallas-b** [luongvo/GmailBackground#2]
Keep getting "Error sending email, please check conection".
tried with both wifi and mobile data. Less secure apps is enabled

**Comment by kevin-fallas-b** [comment]
noticed it only fails when i try to send an attachment

**Comment by luongvo** [comment]
@kevin-fallas-b okay, I'm trying to reproduce that bug and resolve it

**Comment by luongvo** [comment]
@kevin-fallas-b please follow the example at https://github.com/luongvo/GmailBackground/commit/b1f8652e3ed4a2c1b557412d8a251f285ee1cdd7 when using attachment, no issue occurred
