### ISSUE TITLE
attach img

### ISSUE THREAD

**Issue by ragabhesham3** [luongvo/GmailBackground#25]
can you make an example of how to take file from openFilePicker and onActivityResult to put in .withattachment()
i tried a lot of things and can't do that

**Comment by luongvo** [comment]
@ragabhesham3 for attachment, you can set it via `.withAttachments(Environment.getExternalStorageDirectory().getPath() + "/test.txt")` config. In this example, we need to provide the path to the attached file on sdcard, you can find many examples to guide you on the way to pick and get the file path from sdcard.
