### ISSUE TITLE
Oops,error sending email

### ISSUE THREAD

**Issue by imgsingh** [luongvo/GmailBackground#3]
com.creativityapps.gmailbackground E/HAL: Dawei load: module=/system/lib64/hw/gralloc.msm8937.so
the above mentioned file has some problem. can you provide me solution to fix it.

**Comment by luongvo** [comment]
@imgsingh could you check your logcat at this time and give me the log

**Comment by imgsingh** [comment]
The file Text.txt is present in storage but it is saying no such file in directory. I have also given all the permission.
12-06 13:27:00.948 17816-18216/com.creativityapps.gmailbackground W/System.err: Caused by: java.io.FileNotFoundException: /storage/emulated/0/Test.txt: open failed: ENOENT (No such file or directory)
12-06 13:27:00.949 17816-18216/com.creativityapps.gmailbackground W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:452)
12-06 13:27:00.949 17816-18216/com.creativityapps.gmailbackground W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:76)
12-06 13:27:00.949 17816-18216/com.creativityapps.gmailbackground W/System.err:     at javax.activation.FileDataSource.getInputStream(FileDataSource.java:110)
12-06 13:27:00.949 17816-18216/com.creativityapps.gmailbackground W/System.err:     at javax.activation.DataHandler.writeTo(DataHandler.java:318)
12-06 13:27:00.949 17816-18216/com.creativityapps.gmailbackground W/System.err:     at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1652)
12-06 13:27:00.949 17816-18216/com.creativityapps.gmailbackground W/System.err:     at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:961)
12-06 13:27:00.949 17816-18216/com.creativityapps.gmailbackground W/System.err:     at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:553)
12-06 13:27:00.949 17816-18216/com.creativityapps.gmailbackground W/System.err:     at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:81)
12-06 13:27:00.949 17816-18216/com.creativityapps.gmailbackground W/System.err:     at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:900)
12-06 13:27:00.950 17816-18216/com.creativityapps.gmailbackground W/System.err:     at javax.activation.DataHandler.writeTo(DataHandler.java:330)
12-06 13:27:00.950 17816-18216/com.creativityapps.gmailbackground W/System.err:     at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1652)
12-06 13:27:00.950 17816-18216/com.creativityapps.gmailbackground W/System.err:     at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1850)
12-06 13:27:00.950 17816-18216/com.creativityapps.gmailbackground W/System.err:     at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1259)
12-06 13:27:00.950 17816-18216/com.creativityapps.gmailbackground W/System.err: 	... 11 more
12-06 13:27:00.950 17816-18216/com.creativityapps.gmailbackground W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
12-06 13:27:00.950 17816-18216/com.creativityapps.gmailbackground W/System.err:     at libcore.io.Posix.open(Native Method)
12-06 13:27:00.950 17816-18216/com.creativityapps.gmailbackground W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
12-06 13:27:00.951 17816-18216/com.creativityapps.gmailbackground W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:438)
12-06 13:27:00.951 17816-18216/com.creativityapps.gmailbackground W/System.err: 	... 23 more
12-06 13:27:01.010 17816-17835/com.creativityapps.gmailbackground E/HAL: Dawei load: module=/system/lib64/hw/gralloc.msm8937.so

**Comment by imgsingh** [comment]
sorry my bad i have given the name Text.txt but it was Test.txt. thanks for the help.
