### ISSUE TITLE
Unable to merge dex

### ISSUE THREAD

**Issue by CarlosMion** [luongvo/GmailBackground#8]
On trying to sync App's Gradle:

Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

if multidex is enabled, the error goes away, but multidexing is slowing my app significantly, is there any other solution to this?

obs: I'm not repeating any library declaration or anything like it

**Comment by luongvo** [comment]
@CarlosMion did you use any libs below in your project?
```
dependencies {
    compile 'com.android.support:support-annotations:25.2.0'
    compile 'com.sun.mail:android-mail:1.5.6'
    compile 'com.sun.mail:android-activation:1.5.6'
}
```
